export default [
  // Lektion 15
  /*
  {
    turkish: "Kütüphane",
    artikel: "die",
    deutsch: "Bibliothek",
    plural: "-en",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Dükkan",
    artikel: "das",
    deutsch: "Geschäft",
    plural: "-e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Liman",
    artikel: "der",
    deutsch: "Hafen",
    plural: "-:",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Yurt",
    artikel: "die",
    deutsch: "Jugendherberge",
    plural: "-n",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Anaokulu",
    artikel: "der",
    deutsch: "Kindergarten",
    plural: "-:",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Pazar",
    artikel: "der",
    deutsch: "Markt",
    plural: "-:e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Park",
    artikel: "der",
    deutsch: "Park",
    plural: "-s",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Belediye binası",
    artikel: "das",
    deutsch: "Rathaus",
    plural: "-:er",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Şato",
    artikel: "das",
    deutsch: "Schloss",
    plural: "-:er",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Oyun parkı",
    artikel: "der",
    deutsch: "Spielplatz",
    plural: "-:e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Kule",
    artikel: "der",
    deutsch: "Turm",
    plural: "-:e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Yabancı",
    artikel: "der",
    deutsch: "Ausländer",
    plural: "-",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Manzara",
    artikel: "der",
    deutsch: "Blick",
    plural: "-e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "İnsan",
    artikel: "der",
    deutsch: "Mensch",
    plural: "-en",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Seyahat acentesi",
    artikel: "das",
    deutsch: "Reisebüro",
    plural: "-s",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Tarif",
    artikel: "das",
    deutsch: "Rezept",
    plural: "-e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Tatil",
    artikel: "der",
    deutsch: "Urlaub",
    plural: "-",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Hava",
    artikel: "das",
    deutsch: "Wetter",
    plural: "-",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Eksik olmak",
    artikel: "",
    deutsch: "fehlen",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Ait olmak",
    artikel: "",
    deutsch: "gehören",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Önemli",
    artikel: "",
    deutsch: "wichtig",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Hepsi, herkes",
    artikel: "",
    deutsch: "alle",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "az",
    artikel: "",
    deutsch: "wenig",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "eve",
    artikel: "",
    deutsch: "zu Hause",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },

  */
  //Lektion 16

  /*
  {
    turkish: "Asansör",
    artikel: "der",
    deutsch: "Aufzug",
    plural: "-:e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Duş",
    artikel: "die",
    deutsch: "Dusche",
    plural: "-n",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Televizyon",
    artikel: "der",
    deutsch: "Fernseher",
    plural: "-",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Saç kurutma makinesi",
    artikel: "der",
    deutsch: "Föhn",
    plural: "-e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Misafir",
    artikel: "der",
    deutsch: "Gast",
    plural: "-:e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Kalorifer",
    artikel: "die",
    deutsch: "Heizung",
    plural: "-en",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Klima",
    artikel: "die",
    deutsch: "Klimaanlage",
    plural: "-n",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Bağlantı",
    artikel: "die",
    deutsch: "Verbindung",
    plural: "-en",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Çalar saat",
    artikel: "der",
    deutsch: "Wecker",
    plural: "-",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Haber vermek",
    artikel: "",
    deutsch: "Beschieden sagen",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Yardım çağırmak",
    artikel: "",
    deutsch: "Hilfe rufen",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Getirmek",
    artikel: "",
    deutsch: "bringen",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Çalışmak",
    artikel: "",
    deutsch: "funktionieren",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "İlgilenmek",
    artikel: "",
    deutsch: "kümmern",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Tamir etmek",
    artikel: "",
    deutsch: "reparieren",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Göndermek",
    artikel: "",
    deutsch: "schicken",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Kırık",
    artikel: "",
    deutsch: "kaputt",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Hemen",
    artikel: "",
    deutsch: "sofort",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "İstek",
    artikel: "die",
    deutsch: "Lust",
    plural: "-:e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Kararlaştırmak",
    artikel: "",
    deutsch: "vereinbaren",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Ertelemek",
    artikel: "",
    deutsch: "verschieben",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Uymak",
    artikel: "",
    deutsch: "passen",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Dakik",
    artikel: "",
    deutsch: "pünktlich",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Korku",
    artikel: "die",
    deutsch: "Angst",
    plural: "-:e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Kurs",
    artikel: "der",
    deutsch: "Kurs",
    plural: "-e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Hayat",
    artikel: "das",
    deutsch: "Leben",
    plural: "-",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Toplantı",
    artikel: "die",
    deutsch: "Sitzung",
    plural: "-en",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Saat",
    artikel: "die",
    deutsch: "Stunde",
    plural: "-n",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Kapatmak(elektronik)",
    artikel: "",
    deutsch: "ausmachen",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Tanışmak",
    artikel: "",
    deutsch: "kennenlernen",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Yapmak",
    artikel: "",
    deutsch: "tun",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Beklemek",
    artikel: "",
    deutsch: "warten",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Salak",
    artikel: "",
    deutsch: "dumm",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Soğuk",
    artikel: "",
    deutsch: "kalt",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Komik",
    artikel: "",
    deutsch: "lustig",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Garip",
    artikel: "",
    deutsch: "seltsam",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },

  {
    turkish: "Güvenli",
    artikel: "",
    deutsch: "sicher",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Hiçbir şey",
    artikel: "",
    deutsch: "nichts",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },

  */
  //Lektion 18
  /*
  {
    turkish: "meslek öğrenimi",
    artikel: "die",
    deutsch: "Ausbildung",
    plural: "-en",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "yurt dışı",
    artikel: "das",
    deutsch: "Ausland",
    plural: "-",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "şans",
    artikel: "die",
    deutsch: "Chance",
    plural: "-n",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "yabancı dil",
    artikel: "die",
    deutsch: "Fremdsprache",
    plural: "-n",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "para",
    artikel: "das",
    deutsch: "Geld",
    plural: "-",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "siyasetçi",
    artikel: "der",
    deutsch: "Politiker",
    plural: "-",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "sınav",
    artikel: "die",
    deutsch: "Prüfung",
    plural: "-en",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "şarkıcı",
    artikel: "der",
    deutsch: "Sänger",
    plural: "-",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "ünlü kişi",
    artikel: "der",
    deutsch: "Star",
    plural: "-s",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "tamamlamak",
    artikel: "",
    deutsch: "abschließen",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "kaydolmak",
    artikel: "",
    deutsch: "anmelden",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "hak etmek",
    artikel: "",
    deutsch: "verdienen",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "olmak",
    artikel: "",
    deutsch: "werden",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "istemek",
    artikel: "",
    deutsch: "wollen",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "mutlaka",
    artikel: "",
    deutsch: "unbedingt",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "asla",
    artikel: "",
    deutsch: "auf keinen Fall",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Avrupa",
    artikel: "das",
    deutsch: "Europa",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "ehliyet",
    artikel: "der",
    deutsch: "Führerschein",
    plural: "-e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "enstruman",
    artikel: "das",
    deutsch: "Instrument",
    plural: "-e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "kredi kartı",
    artikel: "die",
    deutsch: "Kreditkarte",
    plural: "-n",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "şarkı",
    artikel: "das",
    deutsch: "Lied",
    plural: "-er",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "motorsiklet",
    artikel: "das",
    deutsch: "Motorrad",
    plural: "-:er",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "dünya",
    artikel: "die",
    deutsch: "Welt",
    plural: "-",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "dilek",
    artikel: "der",
    deutsch: "Wunsch",
    plural: "-:e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "evlenmek",
    artikel: "",
    deutsch: "heiraten",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "koşmak",
    artikel: "",
    deutsch: "laufen",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "seyahat etmek",
    artikel: "",
    deutsch: "reisen",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "temizlemek",
    artikel: "",
    deutsch: "putzen",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },

  {
    turkish: "-sız",
    artikel: "",
    deutsch: "ohne",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  */

  //LEKTION 18
  {
    turkish: "Eczane",
    artikel: "die",
    deutsch: "Apotheke",
    plural: "-n",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "Doktor",
    artikel: "der",
    deutsch: "Doktor",
    plural: "-en",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "ateş",
    artikel: "das",
    deutsch: "Fieber",
    plural: "-",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "öksürük",
    artikel: "der",
    deutsch: "Husten",
    plural: "-",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "ilaç",
    artikel: "das",
    deutsch: "Medikament",
    plural: "-e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "tıp",
    artikel: "die",
    deutsch: "Medizin",
    plural: "-",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "yara bandı",
    artikel: "das",
    deutsch: "Pflaster",
    plural: "-",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "muayenehane",
    artikel: "die",
    deutsch: "Praxis",
    plural: "-en",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "reçete",
    artikel: "das",
    deutsch: "Rezept",
    plural: "-e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "merhem",
    artikel: "die",
    deutsch: "Salbe",
    plural: "-n",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "nezle",
    artikel: "der",
    deutsch: "Schnupfen",
    plural: "-",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "hap",
    artikel: "die",
    deutsch: "Tablette",
    plural: "-n",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "öksürmek",
    artikel: "",
    deutsch: "husten",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "acımak",
    artikel: "",
    deutsch: "wehtun",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "sağlıklı",
    artikel: "",
    deutsch: "gesund",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "hasta",
    artikel: "",
    deutsch: "krank",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "kol",
    artikel: "der",
    deutsch: "Arm",
    plural: "-e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "göz",
    artikel: "das",
    deutsch: "Auge",
    plural: "-n",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "karın",
    artikel: "der",
    deutsch: "Bauch",
    plural: "-:e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "bacak",
    artikel: "das",
    deutsch: "Bein",
    plural: "-e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "göğüs",
    artikel: "die",
    deutsch: "Brust",
    plural: "-:e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "parmak",
    artikel: "der",
    deutsch: "Finger",
    plural: "-",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "ayak",
    artikel: "der",
    deutsch: "Fuß",
    plural: "-:e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "boyun",
    artikel: "der",
    deutsch: "Hals",
    plural: "-:e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "el",
    artikel: "die",
    deutsch: "Hand",
    plural: "-:e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "diz",
    artikel: "das",
    deutsch: "Knie",
    plural: "-",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "kafa",
    artikel: "der",
    deutsch: "Kopf",
    plural: "-:e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "burun",
    artikel: "die",
    deutsch: "Nase",
    plural: "-n",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "ağız",
    artikel: "der",
    deutsch: "Mund",
    plural: "-:er",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "kulak",
    artikel: "das",
    deutsch: "Ohr",
    plural: "-en",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "sırt",
    artikel: "der",
    deutsch: "Rücken",
    plural: "-",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "diş",
    artikel: "der",
    deutsch: "Zahn",
    plural: "-:e",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "kalmak",
    artikel: "",
    deutsch: "bleiben",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "vermek",
    artikel: "",
    deutsch: "geben",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "-meli -malı",
    artikel: "",
    deutsch: "sollen",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "yüksek",
    artikel: "",
    deutsch: "hoch",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
  {
    turkish: "karşı",
    artikel: "",
    deutsch: "gegen",
    plural: "",
    artikelState: false,
    deutschState: false,
    pluralState: false,
  },
];
